apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: app-my-first-kafka-service
  name: dev-app-my-first-kafka-service
  namespace: openshift-gitops
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/dev/apps/app-my-first-kafka-service/overlays
    repoURL: https://github.com/DuncanDoyle/my-first-kafka-service-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
